# Generated by Django 4.2.24 on 2025-09-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_item_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['category'],
            },
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Вещь', 'verbose_name_plural': 'Вещи'},
        ),
    ]
