# Generated by Django 4.2.24 on 2025-09-30 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_alter_item_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='store.category'),
        ),
    ]
