# Generated by Django 4.2.24 on 2025-09-30 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_item_category_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='store.category'),
        ),
    ]
