# Generated by Django 4.2.24 on 2025-09-30 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_item_category_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name'], 'verbose_name': 'Вещь', 'verbose_name_plural': 'Вещи'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
    ]
